# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sys
from PyQt5.QtWidgets import QApplication, QMainWindow
from addEditCoffeeForm import Ui_Form as addEditCoffeeForm
import sqlite3

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(10, 10, 770, 450))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.AddButton = QtWidgets.QPushButton(self.centralwidget)
        self.AddButton.setGeometry(QtCore.QRect(10, 470, 150, 25))
        self.AddButton.setObjectName("AddButton")
        self.EditButton = QtWidgets.QPushButton(self.centralwidget)
        self.EditButton.setGeometry(QtCore.QRect(630, 470, 150, 25))
        self.EditButton.setObjectName("EditButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.database = 'data/coffee.sqlite'
        self.load_table()
        self.AddButton.clicked.connect(self.add)
        self.EditButton.clicked.connect(self.edit)

    def load_table(self):
        con = sqlite3.connect(self.database)
        cur = con.cursor()
        lest = cur.execute('select * from coffee').fetchall()
        bar = cur.execute('pragma table_info(coffee)').fetchall()
        for i in range(len(bar)):
            bar[i] = bar[i][1]
        self.tableWidget.setColumnCount(len(bar))
        self.tableWidget.setRowCount(len(lest))
        self.tableWidget.setHorizontalHeaderLabels(bar)
        for i, elem in enumerate(lest):
            for j, val in enumerate(elem):
                self.tableWidget.setItem(i, j, QtWidgets.QTableWidgetItem(str(val)))
        for i in range(7):
            self.tableWidget.setColumnWidth(i, self.tableWidget.width() / 7.05)
        con.close()

    def add(self):
        addForm = addEditCoffeeForm(self)
        addForm.load_combo_box()

    def edit(self):
        con = sqlite3.connect(self.database)
        cur = con.cursor()
        editForm = addEditCoffeeForm(self)
        editForm.NameLineEdit.setText(self.tableWidget.item(self.tableWidget.currentRow(), 1).text())
        grade = cur.execute('select name from grade_of_coffee where id = ?',
                            (self.tableWidget.item(self.tableWidget.currentRow(), 2).text(),)).fetchone()[0]
        con.close()
        editForm.GradeComboBox.addItem(grade)
        editForm.StatusSpinBox.setValue(int(self.tableWidget.item(self.tableWidget.currentRow(), 3).text()))
        editForm.DescriptionLineEdit.setText(self.tableWidget.item(self.tableWidget.currentRow(), 4).text())
        editForm.PriceLineEdit.setText(self.tableWidget.item(self.tableWidget.currentRow(), 5).text())
        editForm.VolumeLineEdit.setText(self.tableWidget.item(self.tableWidget.currentRow(), 6).text())
        editForm.id = int(self.tableWidget.item(self.tableWidget.currentRow(), 0).text())
        editForm.load_combo_box()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.AddButton.setText(_translate("MainWindow", "Add"))
        self.EditButton.setText(_translate("MainWindow", "Edit"))

# Наследуемся от виджета из PyQt5.QtWidgets и от класса с интерфейсом
class MyWidget(QMainWindow, Ui_MainWindow):
    def __init__(self):
        super().__init__()
        self.setupUi(self)


def except_hook(cls, exception, traceback):
    sys.__excepthook__(cls, exception, traceback)


if __name__ == '__main__':
    app = QApplication(sys.argv)
    ex = MyWidget()
    ex.show()
    sys.excepthook = except_hook
    sys.exit(app.exec_())
